development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: martincarreroschmidt
  password: 1Minnrt!
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: martincarreroschmidt
  password: 1Minnrt!